import type { Metadata } from "next";
import "./globals.css";
import { Geist, Geist_Mono, Playfair_Display, Great_Vibes, Newsreader } from "next/font/google";

// mevcut fontların tanımı (sende zaten var)
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });
const playfair  = Playfair_Display({ subsets: ["latin"], weight: ["400","500","700"], style: ["normal","italic"], variable: "--font-playfair" });
const greatVibes = Great_Vibes({ subsets: ["latin"], weight: ["400"], variable: "--font-greatvibes" });

// ✅ Jamie fontu
const newsreader = Newsreader({
  subsets: ["latin"],
  weight: ["400","500","800"],
  style: ["normal","italic"],
  variable: "--font-newsreader",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} ${greatVibes.variable} ${newsreader.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
